# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: UI Project CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload extent report results to Github
      if: always()
      run: |
         git config user.email "hendfouda@gmail.com"
         git config user.name "hFouda43"
         git add target
         git commit -m "adding newly generated reports results"
         git push -u origin master
      shell: bash
      
    - name: Upload TestNG report results to Calliope PRo Platform
      if: always()
      run: |
       curl -X POST
       "https://app.calliope.pro/api/v2/profile/${{secrets.CALLIOPE_PROFILE_ID}}/import/testng"
       -H "Content-Type: multipart/form-data"
       -H "x-api-key:${{secrets.MY_CALLIOPE_API_KEY}}"
       -F "file[]=@target/surefire-reports/TEST-TestSuite.xml"
       
